### ISSUE TITLE
Include Evalb

### ISSUE THREAD

**Issue by cscherrer** [GaloisInc/ppaml-cp5#1]
Calling `make test` from the `demo` directory gives this:
```
~/galois/ppaml/challenge-problems/ppaml-cp5/demo$ make test
../EVALB/evalb does not exist. You need to download EVALB.
Makefile:26: recipe for target 'evalb' failed
make: *** [evalb] Error 1
```
It works fine after the Evalb directory is moved into the right place. Making Evalb part of the repository would make this easier.

The "latest version" from [the Evalb web page](http://nlp.cs.nyu.edu/evalb/) includes an executable that works on my system. If this is a problem on other systems, maybe compiling Evalb should be included as a dependency in the Makefile. Any objections?

Thanks!

**Comment by hhexiy** [comment]
added.

**Comment by hhexiy** [comment]
well, not quite.. I'm checking if evalb works by checking it's return code but "evalb -h" returns 1. Any idea how to do it?

**Comment by cscherrer** [comment]
Maybe it needs to be recompiled - what's your system setup?

I'm using Ubuntu 14.10, and my output is like this:
```
￼~/galois/ppaml/challenge-problems/ppaml-cp5/EVALB$ ./evalb -h
 evalb [-dDh][-c n][-e n][-p param_file] gold-file test-file  
                                                         
    Evaluate bracketing in test-file against gold-file.  
    Return recall, precision, F-Measure, tag accuracy.              
                                                         
  <option>                                               
    -d             debug mode                            
    -D             debug mode plus bracketing info       
    -c n           cut-off length forstatistics (def.=40)
    -e n           number of error to kill (default=10)  
    -p param_file  parameter file                        
    -h    help                                           
```

**Comment by hhexiy** [comment]
Yes, I got the same output. But if you echo $? it's 1 instead of 0..

I just pushed a new version of the Makefile. For now I'm just comparing the
output of evalb.

**Comment by cscherrer** [comment]
Mine returns 0 now. @hhexiy ok to close?

**Comment by hhexiy** [comment]
Yes.
