### ISSUE TITLE
What is the layout of the training corpus?

### ISSUE THREAD

**Issue by axch** [GaloisInc/ppaml-cp5#10]
The submission instructions say that run.sh should accept a command line argument indicating the directory where the training corpus will be located.  How will that corpus be laid out?  One big file of trees? Section directories with *.parse files and other files, like the Octonotes corpus?

**Comment by hhexiy** [comment]
It should be a single file.

**Comment by axch** [comment]
Can we rely on the file name or some pattern by which it can be found, or should we read, say, all non-directory files in the data input path?

**Comment by hhexiy** [comment]
The script uses the file named sample_train.txt, but you can change it.

**Comment by probinso** [comment]
The file will be called `sample_train.txt` .
