### ISSUE TITLE
Problem parsing/evaluating output

### ISSUE THREAD

**Issue by jberkes** [GaloisInc/ppaml-cp5#11]
We ran the evaluator on some sample output provided by a team's smoketest process. Their code did generate the three desired output files (pcfgla.grammar, pcfgla.lexicon, pcfgla.states).  We invoked the evaluator using:
`./eval.sh /tmp/5micro/ ./demo/data /tmp/sampleoutput`

However, we then got an error and crash:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at edu.berkeley.nlp.PCFGLA.ReadGrammar.readStates(ReadGrammar.java:158)
        at edu.berkeley.nlp.PCFGLA.ReadGrammar.main(ReadGrammar.java:356)
```

We uploaded a tar file containing the sample output, and put it in owncloud under `UMD/from_galois`. Here is a link to it:
https://owncloud.galois.com/public.php?service=files&t=e78fe79d5b0f822d132d6409e56f36d6

Could you please take a look and see why this did not parse/evaluate?

**Comment by hhexiy** [comment]
The delimiter in *.states should be a tab instead of a white space. Replace
the whitespaces and it will work.

However, my test run shows that there are lots unknown words/signatures. Is
this model trained on a small training set?

**Comment by jberkes** [comment]
Yes the model was trained on the small set (the micro set).

We will go and try the whitespace change as per your suggestion. Thanks,

**Comment by jberkes** [comment]
I changed the delimeter in *.states from a space to a tab character. To get it to work in the evaluator, I also had to remove the arrows in *.lexicon.  It does appear to work, though.

Please look at the other ticket regarding the arrow issue because there is a mismatch in the specification. Thanks for the assistance!
