### ISSUE TITLE
Conflicting information in cp5 output_format.txt

### ISSUE THREAD

**Issue by jberkes** [GaloisInc/ppaml-cp5#12]
Looking at this part of the documentation, the lexicon specification line 66
https://github.com/GaloisInc/ppaml-cp5/blob/master/doc/output_format.txt#L66

Your specification first includes an arrow '->' but it's followed by an example that does not include the arrow. This seems to conflict.

Could you please clarify whether there should be an arrow in the lexicon, and update the documentation accordingly? Thanks.

**Comment by jberkes** [comment]
Note that, by running it, I found that the evaluator will only work if the arrows are removed from the lexicon file.

If that's the desired behaviour, the output_format.txt should be changed and should not mention any arrows.

**Comment by hhexiy** [comment]
Hi,

Sorry for the confusion. I believe the arrows are to indicate the
generative behavior. All formats should follow the examples.

**Comment by probinso** [comment]
Can you please correct the documentation

**Comment by hhexiy** [comment]
done.

**Comment by probinso** [comment]
Thanks :)
