### ISSUE TITLE
Empty parses

### ISSUE THREAD

**Issue by cscherrer** [GaloisInc/ppaml-cp5#13]
Feeding the three output files from one of the teams into the parser currently results in parses that each look like `(())`, and the result of evalb is NaN. It doesn't throw any other errors.

We thought this could be coming from words in the test corpus that don't show up in the training corpus. To test this, we un-parsed the first sentence of the training corpus and tried to parse it. This resulted in the same error, so missing words are not the (only) problem.

We need to be able to tell if this is due to a problem with the team's file format, or a bug in the parser itself. We'll put the grammar and test data files in Owncloud:
https://owncloud.galois.com/public.php?service=files&t=ebdc58ef51c3a98e55efb940c4e072b8

Thanks!

**Comment by cscherrer** [comment]
We just noticed that the grammar file does not seem to be binarized - there are lines like this:
```
X^g_0 -> DT_0 0.03352141
```

Can you confirm that the parser requires binarized input in order to work properly? Is there a workaround for non-binarized grammars?

Thanks.

**Comment by hhexiy** [comment]
It should accept unary and binary rules. Could you send me the file? I can try to debug. Thanks!

--sent from mobile

**Comment by cscherrer** [comment]
Philip uploaded it to owncloud - link is in the original post

**Comment by hhexiy** [comment]
Thanks. What is the set that this grammar is trained on?

**Comment by cscherrer** [comment]
It was trained on the data set called `quarter`.

**Comment by probinso** [comment]
I have renamed the first uploaded `sample_files.tar.bz2` to `team_one.tar.bz2` and uploaded a second `team_two.tar.bz2` to help diagnose the problem. It looks like `team_one` is not producing output correctly.

**Comment by hhexiy** [comment]
Thanks. I tried to debug last night and it doesn't seem to be a problem of
the format or I/O because the grammar is correctly loaded. The parser
wasn't able to find a valid parse and the inside score at the root is 0.
I'll look more into this issue later today.

**Comment by cscherrer** [comment]
Great, thank you. I thought it could be that somehow the `team_one` grammar may be malformed, maybe giving every parse probability zero or some similar problem. Not sure if there's an easy way to check for problems like this.

**Comment by hhexiy** [comment]
I think I found the bug. Somehow the BerkeleyParser requires the first
grammar state to be a grammar tag, i.e. the first line in the .state file
should be a parent in a rule instead of a POS tag. I tried to remove the
constraint but got a nullpointer exception.

I think for now an easy fix is to always write "ROOT 1" as the first line
of the .state file. Then it should work.

Since the test file may contains word signatures that are not in the
grammar, evalb may report "length unmatched" errors. The current setting
will stop the evaluation if the number of errors is larger than 10. Shall
we set it to a very large number so that we can get scores anyway?

**Comment by cscherrer** [comment]
Great, thank you! We'll let you know soon if this fixes the issue.

**Comment by cscherrer** [comment]
Ok, this seems to fix things. We're thinking of post-processing like this:
1. If "ROOT\t1" is a line, then move it to the top
2. If "ROOT\t1" is not in the file, then add it at the top of the file

Can you confirm that this is a "safe" thing to do - that it will not affect the parse results?
Thanks!

**Comment by hhexiy** [comment]
Yes, except that "ROOT\t1" should always be in the output file. If it's
not, probably something went wrong when inferring the grammar.

**Comment by cscherrer** [comment]
Philip modified `eval.sh` to force the first entry accordingly.
