### ISSUE TITLE
run.sh support for latent annotations

### ISSUE THREAD

**Issue by cscherrer** [GaloisInc/ppaml-cp5#14]
The teams will need to provide a `run.sh` script that fits either the usual (fixed) latent annotation model or the HDP-LA model. For team that implement the fixed LA model, they will need to specify the number of latent annotations in a config file (like `solution-fixedLA-evaluation`).

For comparison, we'll also need to be able to control our run.sh invocation of the Berkeley Parser in a similar way. Here's a link to where we modified our run.sh that extracts this parameter from a config file:
    https://github.com/GaloisInc/ppaml-cp5/blob/master/run.sh#L15

I remember something about Petrov's implementation using a "split-merge" approach. Can the number of latent annotations be specified a priori in this way? If so, can you modify the `run.sh` script to do this?

**Comment by hhexiy** [comment]
hmmm.. I'm not quite sure what need to be changed here. The LA information
is all in the .state and .grammar file (see my previous email). And the
Berkeley parser will parse based on those grammar files.

**Comment by cscherrer** [comment]
The concern here is the generation of grammars to use for comparison. Ideally we'd like to generate grammars for varying numbers of latent annotations, tracking F1 and training time for each. Then we can use these for comparison to whatever the teams provide.

**Comment by hhexiy** [comment]
The BerkeleyParser does not specify the exact number of latent annotations,
because some POS tags is unlikely to have multiple states. For example in
the attached snapshot, some tags have >10 states while some only have 3.

The number of annotations can be roughly controlled by the number of
split-merge iterations by the arugument -SMcycles, the default is 6 and the
baseline is 0.

**Comment by cscherrer** [comment]
Ok. So If I understand, we could evaluate results for varying numbers of split/merge cycles and use this as a baseline. For each POS, we would potentially have a differing number of annotations. Maybe the comparison could then be in terms of the total number of annotated non-terminals.

Does that sound reasonable?

**Comment by hhexiy** [comment]
>
> Maybe the comparison could then be in terms of the total number of
> annotated non-terminals.


Sure. I think this is fine. We could plot Pareto curves, although the total
number of annotations of the baseline and the submitted model may be
different.

**Comment by cscherrer** [comment]
Great. We had a modification to `run.sh` that takes the number of annotations as input (described above in the issue).

Can you modify `run.sh` to instead extract the number of split/merge passes from the config file?

For the comparison, is the number of nonterminals just the number of lines in the grammar file? Or is this something we'll need to have teams return as part of the solution?

**Comment by hhexiy** [comment]
>
> Can you modify run.sh to instead extract the number of split/merge passes
> from the config file?
>
Sure. But now I'm not sure what is in the config file.. I don't remember
that I used that. Is this recently added? Could you give an example/format
of it?

For the comparison, is the number of nonterminals just the number of lines
> in the grammar file? Or is this something we'll need to have teams return
> as part of the solution?
>

It is the sum of numbers in the second column in the .states file, i.e. sum
of number substates for each nonterminal in the non-split grammar.

**Comment by cscherrer** [comment]
>> Can you modify run.sh to instead extract the number of split/merge passes from the config file?

> Sure. But now I'm not sure what is in the config file.. I don't remember that I used that. Is this recently added? Could you give an example/format of it?

The config file is used as an input to `run.sh`, and allows specification of tunable parameters like the number of split/merge passes, or number of particles in a particle filter.

The format is entirely up to you. Because the teams' implementations can be so different, they can have entirely different config file formats. the important thing is that it should be obvious how to adjust any knobs that make a difference.

> It is the sum of numbers in the second column in the .states file, i.e. sum of number substates for each nonterminal in the non-split grammar. 

Ok, great. It sounds like it should be easy to extract this - we'll give it a go. If we run into trouble we may ask you to write a script, but at this point I don't think that will be necessary.

Let me know if everything is clear, and we can close this issue.

Thanks!

**Comment by cscherrer** [comment]
@hhexiy Just checking about this - does `run.sh` now include a way to specify the number of split/merge passes?

**Comment by hhexiy** [comment]
Sorry, I completely forgot about this... I just made the change and pushed
it (run.sh and config).

I think the original version uses `jq` to parse a json file (?). I don't
have this tool for now, so I just source the config file. Let me know if
you'd prefer to keep it. Thanks!

Sorry about the delay!!

He

**Comment by cscherrer** [comment]
Great, thank you! For the config file, whatever is easy for you is totally fine.

@probinso and @mhuesch will be working on an end-to-end run soon, so they'll update if they see more issues.

I'll leave closing this issue to one of them once they confirm it's all set.

**Comment by mhuesch** [comment]
Hi HeHe,

@probinso and I were running through the workflow, and `eval.sh` returns a non-zero exit code for us and does not produce an f1 score. Could you look into why that is happening?

Thanks!
Michael

**Comment by hhexiy** [comment]
What are the error message? Does it happen just to a specific file?

**Comment by mhuesch** [comment]
Sorry, my last message was not particularly descriptive!

```
$ ./run.sh ./config ./demo/data/ /tmp/output-5/ /tmp/log
$ ./eval.sh /tmp/output-5/ demo/data/ /tmp/eval-5
```
are the commands I run. The last line of output from the second command is `evaluatiing exited with return code 1`.

One additional detail is that I wasn't able to run `evalb` at first, because it was compiled for a 32-bit architecture. So I had to run `cd EVALB && make clean && make` before the above 2 commands to rebuild `evalb`.

I also ran it with the datasets from `5-datasets-partitioned.tar.bz2` in Midas and they also finished with `evaluatiing exited with return code 1`. Let me know if there are other things I can run to help narrow down the failure!

**Comment by hhexiy** [comment]
Are you able to run the demo? What are the error messages when you directly
call `evalb <gold_file> <parsed_file>`? I think I need to see the input
file to be more helpful :). Could you attach or maybe paste part of the
files, so that I can run with them?

**Comment by mhuesch** [comment]
Output of running `evalb`:
```
ppamlsys :: ~/git/ppaml-cp5 ‹master*› » ./EVALB/evalb ./demo/data/sample_gold.txt /tmp/eval-5/parsed.txt
  Sent.                        Matched  Bracket   Cross        Correct Tag
 ID  Len.  Stat. Recal  Prec.  Bracket gold test Bracket Words  Tags Accracy
============================================================================
1 : Length unmatch (31|8)
   1   31    1    0.00   0.00     0      0    0      0      0     0     0.00
2 : Length unmatch (22|40)
   2   22    1    0.00   0.00     0      0    0      0      0     0     0.00
3 : Length unmatch (21|31)
   3   21    1    0.00   0.00     0      0    0      0      0     0     0.00
4 : Length unmatch (9|35)
   4    9    1    0.00   0.00     0      0    0      0      0     0     0.00
5 : Length unmatch (23|26)
   5   23    1    0.00   0.00     0      0    0      0      0     0     0.00
6 : Length unmatch (13|17)
   6   13    1    0.00   0.00     0      0    0      0      0     0     0.00
7 : Length unmatch (20|30)
   7   20    1    0.00   0.00     0      0    0      0      0     0     0.00
8 : Length unmatch (76|6)
   8   76    1    0.00   0.00     0      0    0      0      0     0     0.00
9 : Length unmatch (9|7)
   9    9    1    0.00   0.00     0      0    0      0      0     0     0.00
10 : Length unmatch (16|36)
  10   16    1    0.00   0.00     0      0    0      0      0     0     0.00
11 : Length unmatch (17|25)
  11   17    1    0.00   0.00     0      0    0      0      0     0     0.00
12 : Length unmatch (15|16)
```

The file `/tmp/eval-5/parsed.txt` is from my previous run of `eval.sh`. Here is `parsed.txt`: [parsed.txt](https://github.com/GaloisInc/ppaml-cp5/files/10981/parsed.txt)

**Comment by hhexiy** [comment]
It says Length unmatch, which means the parsed sentence and the gold
sentence have different number of words. Could you double check or attach
the gold file?

**Comment by mhuesch** [comment]
Right, it seems like the `parsed.txt` output isn't the right width. I'm using the [gold file](https://github.com/GaloisInc/ppaml-cp5/blob/master/demo/data/sample_gold.txt) which came from the repo. Is that the file you've been using in your testing?

**Comment by hhexiy** [comment]
I think the parsed.txt is for the test sentences. The gold file from the
repo is just a sample file for demo. You should use the gold file
corresponding to the parsed.txt, which should be on midas or some cloud?

**Comment by mhuesch** [comment]
Ah, you are correct. My mistake.

It seems that the issue has to do with the `new.prm` file passed to `evalb`. See 
[evalb-with-prm.txt](https://github.com/GaloisInc/ppaml-cp5/files/11107/evalb-with-prm.txt) and 
[evalb-without-prm.txt](https://github.com/GaloisInc/ppaml-cp5/files/11108/evalb-without-prm.txt). The commands run are the first line of each file. Thanks!

**Comment by mhuesch** [comment]
Also, I ran into the same issue described [here](https://github.com/GaloisInc/ppaml-cp5/issues/8), which I resolved by making the changes described in this [patch](https://github.com/GaloisInc/ppaml-cp5/files/11124/java-version-change.txt). Is that the correct jar file to be using? If so I will commit the changes.

**Comment by mhuesch** [comment]
I've tested with the `5-datasets-partitioned.tar.bz2` data from Midas and also reports a "Length unmatch" when `evalb` is passed `-p ${evalb_param}` in `eval.sh`. Commenting out the -p flag causes the evaluation to succeed and return a reasonable seeming F1 measure.

**Comment by hhexiy** [comment]
new.prm has some options (QUOTE_LABEL, DELETE_LABEL) to correct mismatch in
labels of quotes and ignore some labels, that might be causing problems. I
have committed a new new.prm, so that the only thing it adds to the default
options is to ignore ROOT.
Could you check again? Thanks!

**Comment by mhuesch** [comment]
Cool, it works now. Thanks for your help!
