### ISSUE TITLE
model spec in grammar files

### ISSUE THREAD

**Issue by cscherrer** [GaloisInc/ppaml-cp5#15]
We need to understand the files specifying the grammar. Are these files flexible enough to represent LA models in addition to PCFG? What about HDP-LA models? It would be great if the same format could be used in all cases.

**Comment by hhexiy** [comment]
The format can be used for grammar with latent states too.
In .state file, the number of states for each tag is specified.
In .grammar file, _<number> specify the annotation for a tag.

**Comment by cscherrer** [comment]
Great, thanks!
