### ISSUE TITLE
Question about LA output from teams

### ISSUE THREAD

**Issue by probinso** [GaloisInc/ppaml-cp5#16]
I can only assign this to one person, but I think that this is better addressed to two.

@hhexiy @cscherrer 

I would like to be able to look at the output from a submitted solution and verify that they are using Latent Annotations, as the second iteration of this challenge problem asks for. What should I be seeing as different in their output to determine this?

**Comment by hhexiy** [comment]
If you look at the .state file, grammar that uses LA should have more than
1 state.

**Comment by hhexiy** [comment]
Also, in the .grammar file, all non-terminals have suffix _0 for grammar
*without* LA; they should have _1, _2 ..., i.e. more states when using LA.

**Comment by probinso** [comment]
Thanks !
