### ISSUE TITLE
`eval.sh` fails on input from a run

### ISSUE THREAD

**Issue by mhuesch** [GaloisInc/ppaml-cp5#18]
Hi Hehe,

I was just trying to evaluate a run and got this output
```
$ ~/git/ppaml-cp5/eval.sh /tmp/peval.m99YoC.CRASH/result /tmp/peval.m99YoC.CRASH/ground_truth /tmp/peval.m99YoC.CRASH/output                                                               
They match!
Reading grammar ...
Calling with { -gr => /tmp/peval.m99YoC.CRASH/result/pcfgla.grammar -lex => /tmp/peval.m99YoC.CRASH/result/pcfgla.lexicon -st => /tmp/peval.m99YoC.CRASH/result/pcfgla.states.fixed -out => pcfgla.gr }
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at edu.berkeley.nlp.PCFGLA.ReadGrammar.readStates(ReadGrammar.java:158)
        at edu.berkeley.nlp.PCFGLA.ReadGrammar.main(ReadGrammar.java:356)
reading grammar exited with return code 1
```
it seems like it is not the same "ArrayIndexOutOfBoundsException" as in https://github.com/GaloisInc/ppaml-cp5/issues/17, as the `pcfgla.grammar` and `pcfgla.states` match up, as the "They match!" output tells us (this is printed from my check script).

I've uploaded the directory which contains the run output as a tar archive (just remove the .txt extension, that is necessary to fool GitHub into letting me upload it). If you extract it and then run the eval.sh script on it (a modification of the above command) hopefully you will see the same output. If you could take a look it would be very helpful!

[evaluation_fail_directory.tar.bz2.txt](https://github.com/GaloisInc/ppaml-cp5/files/33556/evaluation_fail_directory.tar.bz2.txt)

Thanks,
Michael

**Comment by hhexiy** [comment]
The states file uses tab as delimiter, but the crashed file (.state) uses
whitespace..

Also, its lexicon file is in wrong format. Each line should be
[non-terminal] [word] [score]
but the attached .lexicon file has
[non-terminal] -> [word] [score]

He

**Comment by mhuesch** [comment]
Ah, ok thanks! Transforming the pcfgla.states file to have tabs instead of whitespace using `sed -rni 's/^(.*) (.*)$/\1\t\2/p result/pcfgla.states`, and removing the " -> " from lexicon using `sed -rni 's/^(.*) -> (.*)$/\1 \2/p' result/pcfgla.lexicon` allowed the evaluation to complete and yield an F1 score! Great!

Thanks for your help :D
