### ISSUE TITLE
`make test` is slow

### ISSUE THREAD

**Issue by cscherrer** [GaloisInc/ppaml-cp5#2]
I started `make test` about 45 minutes ago. Here's the output so far:
```
~/galois/ppaml/challenge-problems/ppaml-cp5/demo$ make test
java -cp ../lib/BerkeleyParser-1.7.jar edu.berkeley.nlp.PCFGLA.WriteGrammar -gr eng_MLE.gr
Load grammar eng_MLE.gr.
java -cp ../lib/BerkeleyParser-1.7.jar edu.berkeley.nlp.PCFGLA.ReadGrammar -gr eng_MLE.gr.grammar -lex eng_MLE.gr.lexicon -st eng_MLE.gr.states -out eng_MLE.read.gr
Calling with { -gr => eng_MLE.gr.grammar -lex => eng_MLE.gr.lexicon -st => eng_MLE.gr.states -out => eng_MLE.read.gr }
Read 98 states.
Read 4742 rules.
Save grammar to eng_MLE.read.gr
Saving successful.
java -jar ../lib/BerkeleyParser-1.7.jar -noHierarchy -gr eng_MLE.read.gr -inputFile wsj_test.22.txt -nThreads 4 -outputFile wsj_pred.22.txt
Parsing with 4 threads in parallel.
```

It used 4 cores for a few minutes, then dropped down to one core at 100%, and has been going like that for quite a while. 

`ls -alth` shows these files last modified about 45 minutes ago, which must have been immediately after starting:
```
-rw-rw-r-- 1 chad chad 558K Mar  9 11:16 wsj_pred.22.txt
-rw-rw-r-- 1 chad chad 230K Mar  9 11:15 eng_MLE.read.gr
-rw-rw-r-- 1 chad chad 248K Mar  9 11:15 eng_MLE.gr.lexicon
-rw-rw-r-- 1 chad chad 205K Mar  9 11:15 eng_MLE.gr.grammar
-rw-rw-r-- 1 chad chad 1.1K Mar  9 11:15 eng_MLE.gr.info
-rw-rw-r-- 1 chad chad 1.3K Mar  9 11:15 eng_MLE.gr.states
```

Is this the expected behavior?

**Comment by hhexiy** [comment]
There might be a bug when using the non-split grammar. Let me fix that and check again. Could you use eng_sm6_quarter.gr for now?

**Comment by hhexiy** [comment]
I pushed a new version, evalb is added too.

**Comment by cscherrer** [comment]
I'm getting similar behavior when using `eng_sm6_quarter.gr`, except that it's complaining, `unknown signature for word Tax-exempts`.

**Comment by hhexiy** [comment]
unknown signature for word Tax-exempts. This is expected.
 eng_sm6_quarter runs longer. eng_MLE should be fine and runs within 10min
now.

**Comment by hhexiy** [comment]
I attached the output from my run of eng_MLE.gr.

**Comment by cscherrer** [comment]
Where did you attach the output?

`eng_MLE` is still taking over 30 minutes for me, and still hasn't run to completion. @probinso can you try this on your machine so I know it's not something weird about my setup?

**Comment by hhexiy** [comment]
I replied in the email but seems the attachment is not uploaded to github..
It is pasted below.

I probably didn't update the jar file. Could you try now?

-- All --
Number of sentence        =   1700
Number of Error sentence  =      0
Number of Skip  sentence  =      0
Number of Valid sentence  =   1700
Bracketing Recall         =  56.68
Bracketing Precision      =  62.43
Bracketing FMeasure       =  59.41
Complete match            =   0.00
Average crossing          =   3.51
No crossing               =  24.00
2 or less crossing        =  47.29
Tagging accuracy          =  93.06

-- len<=40 --
Number of sentence        =   1578
Number of Error sentence  =      0
Number of Skip  sentence  =      0
Number of Valid sentence  =   1578
Bracketing Recall         =  57.55
Bracketing Precision      =  63.40
Bracketing FMeasure       =  60.34
Complete match            =   0.00
Average crossing          =   3.09
No crossing               =  25.79
2 or less crossing        =  50.89
Tagging accuracy          =  92.96

**Comment by cscherrer** [comment]
It's running ok for Philip, but still not for me. We're wondering if it could be a java version issue.

**Comment by hhexiy** [comment]
I compiled with java 1.8.0_31 because java 1.7 gave me an error.

However, when I googled the error it seems 1.7 compiles okay in IDEs...

**Comment by hhexiy** [comment]
Chad, what's your error? running infinitely? I just tried to use java 1.7
to run but it will simply crash.

**Comment by cscherrer** [comment]
I've tried with Java 1.8, both Oracle and OpenJDK. It runs at 400% for a bit, then goes down to 100% and seems to just hang. 

Can you tell us more about your environment, and maybe if there are any kind of debugging options (neither Philip nor I have much Java experience).

**Comment by hhexiy** [comment]
hmm.. I'm using Redhat 6. What other environment parameters should I check?

What about -nThread 1, and/or using eng_MLE.gr instead of eng_MLE.read.gr?
You can modify the command under target wsj_pred.22.txt.

I don't use java often either :), but for debugging, perhaps try the
following command:

java -cp lib/BerkeleyParser-1.7.jar edu.berkeley.nlp.PCFGLA.GrammarTester
-in demo/eng_MLE.gr -path <path to wsj corpus> -nThread 4 -verbose

This prints out more info. Note that <path to wsj corpus> should points to
the unprocessed treebank and should be the parent directory of wsj/, e.g.
for me it is /fs/clip-corpora/treebank_3/parsed/mrg.

**Comment by probinso** [comment]
On fedora 20, the program runs to completion. However I just did a clean install with our provided Ubuntu environment, and I got the same 'infinate loop' like behaviour that Chad ran into.

The environment setup tools are located here https://owncloud.galois.com/public.php?service=files&t=6af03994fee84518caad6cbf8eb3aa9a and are to be installed to a clean Ubuntu 14.04 release.

I'll continue to investigate, however I figured that it may help to know what we're restricted to work with.

**Comment by hhexiy** [comment]
Thanks. Does it hang only with multiple thread or even a single thread?

**Comment by probinso** [comment]
looks like single thread works fine
unless the deadlock is addressed, we will need the makefile to set execution to a single thread

**Comment by hhexiy** [comment]
I just tried to run the original Berkeley Parser jar on Ubuntu. It fails
with multiple thread too. I'm not sure about the problem yet.
For now I've set nThreads to 1.

**Comment by cscherrer** [comment]
This seems to do it - closing
