### ISSUE TITLE
Execution restrictions - eval.sh

### ISSUE THREAD

**Issue by probinso** [GaloisInc/ppaml-cp5#4]
We will need a script called eval.sh that starts as denoted below, and wraps the evaluator. `$1` and `$2` are directories containing the `solution_ouput` (estimated parse trees) and the `evaluation_data` (true parse trees) . `$3` designates the directory path `resultant_path`, that we will save the evaluation output (F1 score).

```bash
#!/bin/bash -eu

if (( $# != 3 )); then
    printf "Usage: %s solution_output eval_data resultant_path \n" "$0" >&2
    exit 1
fi
mkdir -p "$3"

... continued ...
````

We will need the return code of this script to reflect the return code of evaluator.

The directory names passed in as `$1` `$2` and `$3` are likely to be sub directories of `/tmp/` but this can not be assumed. 

If the teams do not know expected filenames that the evaluator intends to read from `$1` then evaluation script will need to identify the most appropriate contents of `$1`. In order to insure that this isn't a problem, contents of `$1` or `$2` may be fixed or hard coded, but these restrictions must be added to the documentation.

We would like the filenames for output to `$3` to not change due to input paths or values.

If any of this is confusing, then please let me know.

**Comment by hhexiy** [comment]
One question: should I assume evalb has been compiled before executing this
script?

**Comment by probinso** [comment]
Yes you should assume that `evalb` is compiled. We will run `make` before running `eval.sh`

If i'm not mistaken, it looks to me like eval.sh will need the use of `evalb` and `BerkeleyParser-1.7.jar` .  If you place `eval.sh` into the root directory of this repository then the script can call `evalb` with `./EVALB/evalb` and `BerkeleyParser-1.7.jar` with `java -cp ./lib/BerkeleyParser-1.7.jar ...`

**Comment by hhexiy** [comment]
Hi -- I just pushed eval.sh and updated output_format.txt to specify output
file names.
test.txt and gold.txt need to be in directory eval_data.

**Comment by probinso** [comment]
I don't seem to have any `.rules` files in the directory tree after running `make test` from `demo`. Should I be expecting one? Is there an example `.rules` file that I can use for an evaluation run?

I imagine that if I run `make test` from the `demo` directory then I should be able to find all of the nessicary files to complete an evaluation. I am able to find `eng_MLE.gr.{lexicon,states,grammar,info}` which I  presently poll from for `pcfgla.{lexicon,states}`

**Comment by hhexiy** [comment]
Sorry about the confusion. .rules is .grammar. I have changed ".rules" to ".
grammar".
