### ISSUE TITLE
Include public domain corpus

### ISSUE THREAD

**Issue by cscherrer** [GaloisInc/ppaml-cp5#6]
Because of licensing concerns, some teams may not have direct access to the Ontonotes corpus. In order to be able to test their code, they will need at least a "microcorpus" of training and test data similar to `sample.tst` currently in the repository.

Can you include this, and edit the demo to refer to whatever corpus is included? A medium-sized corpus would be great if there is one with something like a BSD license, but I don't know of such a thing existing.

**Comment by hhexiy** [comment]
I put them in demo/data. Each of the files include 100 sentences.

**Comment by cscherrer** [comment]
Looks great, thanks! What's the source of this data? Is there any kind of license for it?

**Comment by hhexiy** [comment]
hmm.. I don't think there's any license for public usage. I just took the
first 100 sentences.

**Comment by tdietterich** [comment]
He He,

Is there a way that we could generate synthetic data for them? For example, can we take a fitted grammar and generate new sentences from it?

--Tom

--
Thomas G. Dietterich, Distinguished Professor Voice: 541-737-5559
School of Electrical Engineering              FAX: 541-737-1300
  and Computer Science                        URL: eecs.oregonstate.edu/~tgd
US Mail: 1148 Kelley Engineering Center
Office: 2067 Kelley Engineering Center
Oregon State Univ., Corvallis, OR 97331-5501

**Comment by hhexiy** [comment]
Yes. It can be generated recursively from the root.

**Comment by probinso** [comment]
Can you pelase remove the micro corpus that you uploaded to github from the repository. The problems are that one of the teams cannot use the license that LDC restricts to, and we do not have the rights publicly re-distribute it.

We are excited about this synthetic corpus. We would like a synthetic microcorpus that is small for development, and testing purposes uploaded to replace the present one on the repository.

We would also like a synthetic corpus approximately the same size as the ontonotes corpus uploaded to ownCloud, such that we can place it on Midas for the teams. This is lower priority than the microcorpus.

**Comment by hhexiy** [comment]
I have removed the sample data and am working on the synthetic corpus.

I'm at home in China now, so I'll have to skip this weeks meeting due to
the time difference :P.

**Comment by probinso** [comment]
I have produced two sample solution invocation scripts. I am using `run.sh` to test the synthetic corpus. 

We would like for `run.sh` to run to completion, and create `.lexicon`, `.grammar`, and `.states` files. I suspect that modifying behaviour with rare words, or missing flags in

```bash
java -cp $jarfile edu.berkeley.nlp.PCFGLA.GrammarTrainer -path $input_dir/sample_train.txt -out $output_dir/$grammar.gr -treebank SINGLEFILE
```

is causing this error.

```Exception in thread "main" java.lang.ClassCastException:
  edu.berkeley.nlp.PCFGLA.SophisticatedLexicon cannot be cast to edu.berkeley.nlp.PCFGLA.SimpleLexicon at 
    edu.berkeley.nlp.PCFGLA.WriteGrammar.main(WriteGrammar.java:181)```

`shortcut_run.sh` uses the predetermined  grammar and works, as an example script but doesn't test the synthetic corpus.

**Comment by hhexiy** [comment]
Hi Philip,

When training the grammar, the flag "-simpleLexicon" should be specified. I
think that will fix the error.

Thanks,
He

**Comment by probinso** [comment]
! thanks
